import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Activity, ArrowDown, ArrowUp, CalendarPlus, Check, Edit2, KeyRound, Layers3, Plus, Search, Settings2, Shield, ToggleLeft, ToggleRight, UserPlus, Users } from 'lucide-react'
import { useStore } from '../store/useStore.jsx'
import { useLang } from '../lib/i18n.jsx'
import { ACCESS_LEVEL_LABELS, hasPermission, isSuperAdminUser } from '../lib/permissions.js'
import { Badge, Btn, Card, ConfirmDialog, EmptyState, Input, Modal, SearchInput, Select, Tabs, Textarea } from '../components/ui'

const blankRole={name:'',categoryId:'',description:'',displayOrder:0,active:true}
const blankCategory={name:'',description:'',displayOrder:0,active:true}

function Overview({store,isAr,onTab,navigate}){
  const now=new Date().toISOString().slice(0,10)
  const stats=[
    [isAr?'إجمالي الأعضاء':'Total members',store.people.length,'indigo'],
    [isAr?'الأعضاء النشطون':'Active members',store.people.filter(person=>person.status==='active').length,'green'],
    [isAr?'الأعضاء غير النشطين':'Inactive members',store.people.filter(person=>person.status==='inactive').length,'slate'],
    [isAr?'الأدوار النشطة':'Active roles',store.worshipRoles.filter(role=>role.active).length,'purple'],
    [isAr?'الخدمات القادمة':'Upcoming services',store.services.filter(service=>service.date>=now&&!['completed','cancelled'].includes(service.status)).length,'blue'],
    [isAr?'الفعاليات القادمة':'Upcoming events',store.events.filter(event=>event.date>=now&&event.status!=='cancelled').length,'yellow'],
    [isAr?'الدعوات المعلقة':'Pending invitations',store.invitations.filter(invitation=>invitation.status==='pending').length,'orange'],
  ]
  return <div className="space-y-5">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(([label,value,color])=><Card key={label} className="p-4"><div className="text-2xl font-bold text-slate-800">{value}</div><Badge color={color}>{label}</Badge></Card>)}</div>
    <Card className="p-5"><h2 className="mb-4 font-semibold text-slate-800">{isAr?'إجراءات سريعة':'Quick actions'}</h2><div className="flex flex-wrap gap-2">
      {hasPermission(store.currentUser,'roles.manage')&&<Btn icon={<Plus size={15}/>} onClick={()=>onTab('roles')}>{isAr?'إضافة دور':'Add role'}</Btn>}
      {hasPermission(store.currentUser,'invitations.manage')&&<Btn variant="secondary" icon={<UserPlus size={15}/>} onClick={()=>navigate('/invitations')}>{isAr?'دعوة عضو':'Invite member'}</Btn>}
      <Btn variant="secondary" icon={<CalendarPlus size={15}/>} onClick={()=>navigate('/services')}>{isAr?'إنشاء خدمة':'Create service'}</Btn>
      <Btn variant="secondary" onClick={()=>navigate('/events')}>{isAr?'إنشاء فعالية':'Create event'}</Btn>
    </div></Card>
    <Card className="p-5"><div className="mb-4 flex items-center gap-2"><Activity size={18} className="text-indigo-600"/><h2 className="font-semibold text-slate-800">{isAr?'آخر النشاطات الإدارية':'Recent admin activity'}</h2></div>
      {store.auditLogs.length===0?<p className="text-sm text-slate-400">{isAr?'لا يوجد نشاط مسجل بعد':'No recorded activity yet'}</p>:<div className="divide-y divide-slate-100">{store.auditLogs.slice(0,8).map(log=><div key={log.id} className="flex items-start justify-between gap-3 py-3"><div><div className="text-sm font-medium text-slate-700">{log.action}</div><div className="text-xs text-slate-400">{log.actor?.name||log.actor?.email||'System'} · {log.entity_type}</div></div><time className="text-xs text-slate-400" dateTime={log.created_at}>{new Date(log.created_at).toLocaleString(isAr?'ar-EG':'en-GB')}</time></div>)}</div>}
    </Card>
  </div>
}

function RolesPanel({store,isAr}){
  const [search,setSearch]=useState('');const[categoryFilter,setCategoryFilter]=useState('all');const[status,setStatus]=useState('all')
  const [roleForm,setRoleForm]=useState(null);const[categoryForm,setCategoryForm]=useState(null);const[statusTarget,setStatusTarget]=useState(null);const[replacementId,setReplacementId]=useState('');const[error,setError]=useState('');const[pending,setPending]=useState(false);const[dragId,setDragId]=useState(null)
  const ordered=[...store.worshipRoles].sort((a,b)=>a.displayOrder-b.displayOrder||a.name.localeCompare(b.name))
  const filtered=ordered.filter(role=>(!search||role.name.toLowerCase().includes(search.toLowerCase()))&&(categoryFilter==='all'||role.categoryId===categoryFilter)&&(status==='all'||String(role.active)===status))
  const usageFor=role=>store.roleUsage[role.id]||{
    profile_count:store.people.filter(person=>(person.roleIds||[]).includes(role.id)||(person.roles||[]).includes(role.name)).length,
    assignment_count:store.services.flatMap(service=>service.team||[]).filter(member=>member.roleId===role.id||member.role===role.name).length,
    invitation_count:store.invitations.filter(invitation=>(invitation.roleIds||[]).includes(role.id)||(invitation.roles||[]).includes(role.name)).length,
    request_count:0,
  }
  const saveRole=async()=>{setPending(true);setError('');const result=await store.saveWorshipRole(roleForm);setPending(false);if(result?.error)setError(result.error);else setRoleForm(null)}
  const saveCategory=async()=>{setPending(true);setError('');const result=await store.saveRoleCategory(categoryForm);setPending(false);if(result?.error)setError(result.error);else setCategoryForm(null)}
  const changeStatus=async()=>{setPending(true);setError('');const result=await store.setWorshipRoleStatus(statusTarget.id,!statusTarget.active,replacementId||null);setPending(false);if(result?.error)setError(result.error);else{setStatusTarget(null);setReplacementId('')}}
  const move=async(id,direction)=>{const index=ordered.findIndex(role=>role.id===id);const target=index+direction;if(target<0||target>=ordered.length)return;const next=[...ordered];[next[index],next[target]]=[next[target],next[index]];await store.reorderWorshipRoles(next.map(role=>role.id))}
  const drop=async targetId=>{if(!dragId||dragId===targetId)return;const next=[...ordered];const from=next.findIndex(role=>role.id===dragId);const to=next.findIndex(role=>role.id===targetId);const[item]=next.splice(from,1);next.splice(to,0,item);setDragId(null);await store.reorderWorshipRoles(next.map(role=>role.id))}
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-1 flex-wrap gap-2"><SearchInput className="w-full sm:w-60" value={search} onChange={setSearch} placeholder={isAr?'ابحث في الأدوار...':'Search roles...'}/><Select className="w-full sm:w-44" value={categoryFilter} onChange={event=>setCategoryFilter(event.target.value)}><option value="all">{isAr?'كل الفئات':'All categories'}</option>{store.roleCategories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</Select><Select className="w-full sm:w-36" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">{isAr?'كل الحالات':'All statuses'}</option><option value="true">{isAr?'نشط':'Active'}</option><option value="false">{isAr?'غير نشط':'Inactive'}</option></Select></div><div className="flex gap-2"><Btn variant="secondary" onClick={()=>setCategoryForm({...blankCategory,displayOrder:(store.roleCategories.length+1)*10})}>{isAr?'إدارة الفئات':'Categories'}</Btn><Btn icon={<Plus size={15}/>} onClick={()=>setRoleForm({...blankRole,categoryId:store.roleCategories.find(category=>category.active)?.id||'',displayOrder:(store.worshipRoles.length+1)*10})}>{isAr?'إضافة دور':'Add role'}</Btn></div></div>
    {filtered.length===0?<EmptyState icon={<Layers3/>} title={isAr?'لا توجد أدوار':'No roles found'}/>:<div className="space-y-2">{filtered.map((role,index)=>{const usage=usageFor(role);return <Card key={role.id} className="p-4" onDragOver={event=>event.preventDefault()} onDrop={()=>drop(role.id)}><div draggable onDragStart={()=>setDragId(role.id)} className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="cursor-grab text-slate-300" title={isAr?'اسحب لإعادة الترتيب':'Drag to reorder'}>⋮⋮</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong className="text-slate-800">{role.name}</strong><Badge color={role.active?'green':'slate'}>{role.active?(isAr?'نشط':'Active'):(isAr?'غير نشط':'Inactive')}</Badge><Badge color="indigo">{role.category?.name||store.roleCategories.find(category=>category.id===role.categoryId)?.name||'Other'}</Badge></div>{role.description&&<p className="mt-1 text-sm text-slate-500">{role.description}</p>}<p className="mt-1 text-xs text-slate-400">{usage.profile_count||0} {isAr?'أعضاء':'members'} · {usage.assignment_count||0} {isAr?'تكليفات':'assignments'}</p></div><div className="flex items-center gap-1"><button onClick={()=>move(role.id,-1)} disabled={index===0} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 disabled:opacity-30" aria-label={isAr?'تحريك لأعلى':'Move up'}><ArrowUp size={15}/></button><button onClick={()=>move(role.id,1)} disabled={index===ordered.length-1} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 disabled:opacity-30" aria-label={isAr?'تحريك لأسفل':'Move down'}><ArrowDown size={15}/></button><button onClick={()=>setRoleForm({...role})} className="rounded-lg p-2 text-slate-400 hover:bg-indigo-50 hover:text-indigo-600" aria-label={isAr?'تعديل الدور':'Edit role'}><Edit2 size={15}/></button><button onClick={()=>{setStatusTarget(role);setReplacementId('');setError('')}} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label={role.active?(isAr?'تعطيل الدور':'Disable role'):(isAr?'تفعيل الدور':'Enable role')}>{role.active?<ToggleRight size={19} className="text-emerald-500"/>:<ToggleLeft size={19}/>}</button></div></div></Card>})}</div>}
    <Modal open={!!roleForm} onClose={()=>setRoleForm(null)} title={roleForm?.id?(isAr?'تعديل الدور':'Edit role'):(isAr?'إضافة دور':'Add role')} footer={<><Btn variant="secondary" onClick={()=>setRoleForm(null)}>{isAr?'إلغاء':'Cancel'}</Btn><Btn disabled={pending||!roleForm?.name.trim()||!roleForm?.categoryId} onClick={saveRole}>{pending?'…':(isAr?'حفظ':'Save')}</Btn></>}><div className="space-y-4"><Input required label={isAr?'اسم الدور':'Role name'} value={roleForm?.name||''} onChange={event=>setRoleForm(current=>({...current,name:event.target.value}))}/><Select required label={isAr?'الفئة':'Category'} value={roleForm?.categoryId||''} onChange={event=>setRoleForm(current=>({...current,categoryId:event.target.value}))}>{store.roleCategories.filter(category=>category.active||category.id===roleForm?.categoryId).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</Select><Textarea label={isAr?'الوصف':'Description'} value={roleForm?.description||''} onChange={event=>setRoleForm(current=>({...current,description:event.target.value}))}/><Input type="number" label={isAr?'ترتيب العرض':'Display order'} value={roleForm?.displayOrder||0} onChange={event=>setRoleForm(current=>({...current,displayOrder:Number(event.target.value)}))}/>{error&&<p className="text-sm text-red-600" role="alert">{error}</p>}</div></Modal>
    <Modal open={!!categoryForm} onClose={()=>setCategoryForm(null)} title={isAr?'إدارة فئات الأدوار':'Manage role categories'} footer={<><Btn variant="secondary" onClick={()=>setCategoryForm(null)}>{isAr?'إلغاء':'Cancel'}</Btn><Btn disabled={pending||!categoryForm?.name.trim()} onClick={saveCategory}>{pending?'…':(isAr?'حفظ':'Save')}</Btn></>}><div className="space-y-4"><div className="flex flex-wrap gap-2">{store.roleCategories.map(category=><button type="button" key={category.id} onClick={()=>setCategoryForm({...category})} className={`rounded-lg border px-3 py-2 text-sm ${categoryForm?.id===category.id?'border-indigo-400 bg-indigo-50 text-indigo-700':'border-slate-200 text-slate-600'}`}>{category.name}{!category.active?` · ${isAr?'غير نشطة':'inactive'}`:''}</button>)}<button type="button" onClick={()=>setCategoryForm({...blankCategory,displayOrder:(store.roleCategories.length+1)*10})} className="rounded-lg border border-dashed border-indigo-300 px-3 py-2 text-sm text-indigo-600">+ {isAr?'جديدة':'New'}</button></div><Input required label={isAr?'اسم الفئة':'Category name'} value={categoryForm?.name||''} onChange={event=>setCategoryForm(current=>({...current,name:event.target.value}))}/><Textarea label={isAr?'الوصف':'Description'} value={categoryForm?.description||''} onChange={event=>setCategoryForm(current=>({...current,description:event.target.value}))}/><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Input type="number" label={isAr?'ترتيب العرض':'Display order'} value={categoryForm?.displayOrder||0} onChange={event=>setCategoryForm(current=>({...current,displayOrder:Number(event.target.value)}))}/><label className="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-sm font-medium text-slate-700"><span>{isAr?'الفئة متاحة':'Category active'}</span><input type="checkbox" checked={categoryForm?.active??true} onChange={event=>setCategoryForm(current=>({...current,active:event.target.checked}))}/></label></div>{error&&<p className="text-sm text-red-600" role="alert">{error}</p>}</div></Modal>
    <Modal open={!!statusTarget} onClose={()=>setStatusTarget(null)} title={statusTarget?.active?(isAr?'تعطيل الدور':'Disable role'):(isAr?'تفعيل الدور':'Enable role')} footer={<><Btn variant="secondary" onClick={()=>setStatusTarget(null)}>{isAr?'إلغاء':'Cancel'}</Btn><Btn variant={statusTarget?.active?'danger':'success'} disabled={pending} onClick={changeStatus}>{pending?'…':statusTarget?.active?(isAr?'تعطيل':'Disable'):(isAr?'تفعيل':'Enable')}</Btn></>}><div className="space-y-4">{statusTarget&&(()=>{const usage=usageFor(statusTarget);const total=Number(usage.profile_count||0)+Number(usage.assignment_count||0)+Number(usage.invitation_count||0)+Number(usage.request_count||0);return <><p className="text-sm text-slate-600">{statusTarget.active?(isAr?`هذا الدور مستخدم في ${usage.profile_count||0} ملف عضو و ${usage.assignment_count||0} تكليف. سيبقى في السجل التاريخي.`:`This role is used by ${usage.profile_count||0} members and ${usage.assignment_count||0} assignments. Historical records will remain intact.`):(isAr?'سيظهر الدور مجدداً في التكليفات الجديدة.':'The role will become available for new assignments again.')}</p>{statusTarget.active&&total>0&&<Select label={isAr?'استبدال العضويات والدعوات الحالية (اختياري)':'Replace current memberships and invitations (optional)'} value={replacementId} onChange={event=>setReplacementId(event.target.value)}><option value="">{isAr?'تعطيل فقط — احتفظ بالتاريخ':'Disable only — preserve history'}</option>{store.worshipRoles.filter(role=>role.active&&role.id!==statusTarget.id).map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</Select>}</>})()}{error&&<p className="text-sm text-red-600" role="alert">{error}</p>}</div></Modal>
  </div>
}

function RolePicker({roles,selected,onChange,isAr}){return <fieldset><legend className="mb-2 text-sm font-medium text-slate-700">{isAr?'أدوار التسبيح':'Worship roles'} *</legend><div className="flex flex-wrap gap-2">{roles.filter(role=>role.active||selected.includes(role.id)).map(role=>{const active=selected.includes(role.id);return <button key={role.id} type="button" onClick={()=>onChange(active?selected.filter(id=>id!==role.id):[...selected,role.id])} aria-pressed={active} className={`rounded-lg border px-3 py-2 text-xs font-medium ${active?'border-indigo-600 bg-indigo-600 text-white':'border-slate-200 text-slate-600 hover:border-indigo-300'}`}>{active&&<Check size={11} className="me-1 inline"/>}{role.name}</button>})}</div></fieldset>}

function UsersPanel({store,isAr}){
  const [search,setSearch]=useState('');const[status,setStatus]=useState('all');const[editing,setEditing]=useState(null);const[pending,setPending]=useState(false);const[error,setError]=useState('');const[deactivate,setDeactivate]=useState(null)
  const canEdit=hasPermission(store.currentUser,'users.edit')
  const filtered=store.people.filter(person=>(!search||`${person.name} ${person.email} ${(person.roles||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase()))&&(status==='all'||person.status===status))
  const open=person=>setEditing({...person,roleIds:person.roleIds?.length?person.roleIds:(person.roles||[]).map(name=>store.worshipRoles.find(role=>role.name===name)?.id).filter(Boolean),primaryRoleId:person.primaryRoleId||store.worshipRoles.find(role=>role.name===person.role)?.id||'',accessLevel:person.accessLevel||'member'})
  const save=async()=>{setPending(true);setError('');const result=await store.updatePerson(editing.id,editing);setPending(false);if(result?.error)setError(result.error);else setEditing(null)}
  return <div className="space-y-4"><div className="flex flex-wrap gap-2"><SearchInput className="w-full sm:w-72" value={search} onChange={setSearch} placeholder={isAr?'ابحث بالاسم أو البريد أو الدور...':'Search name, email, or role...'}/><Select className="w-full sm:w-40" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">{isAr?'كل الحالات':'All statuses'}</option><option value="active">{isAr?'نشط':'Active'}</option><option value="inactive">{isAr?'غير نشط':'Inactive'}</option><option value="on-leave">{isAr?'إجازة':'On leave'}</option></Select></div>
    <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">{filtered.map(person=>{const protectedAdmin=['super_admin','admin'].includes(person.accessLevel)&&!isSuperAdminUser(store.currentUser);return <Card key={person.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-slate-800">{person.name}</strong><Badge color={person.status==='active'?'green':'slate'}>{person.status}</Badge><Badge color={person.accessLevel==='super_admin'?'purple':person.accessLevel==='admin'?'indigo':'slate'}>{ACCESS_LEVEL_LABELS[person.accessLevel||'member']?.[isAr?'ar':'en']}</Badge></div><p className="mt-1 truncate text-sm text-slate-500">{person.email}{person.phone?` · ${person.phone}`:''}</p><div className="mt-2 flex flex-wrap gap-1">{(person.roles||[]).map(role=><Badge key={role}>{role}{role===person.primaryRole?' ★':''}</Badge>)}</div><p className="mt-2 text-xs text-slate-400">{isAr?'آخر نشاط':'Last active'}: {person.lastActiveAt?new Date(person.lastActiveAt).toLocaleString(isAr?'ar-EG':'en-GB'):(isAr?'غير متاح':'Not available')}</p></div>{canEdit&&<div className="flex gap-1"><button onClick={()=>open(person)} disabled={protectedAdmin} className="rounded-lg p-2 text-slate-400 hover:bg-indigo-50 hover:text-indigo-600 disabled:cursor-not-allowed disabled:opacity-35" aria-label={protectedAdmin?(isAr?'المسؤول الأعلى فقط يمكنه تعديل المسؤولين':'Only a Super Admin can edit administrators'):(isAr?'تعديل المستخدم':'Edit user')}><Edit2 size={15}/></button>{person.status==='active'&&person.id!==store.currentUser.id&&!protectedAdmin&&<button onClick={()=>setDeactivate(person)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" aria-label={isAr?'تعطيل المستخدم':'Deactivate user'}><ToggleLeft size={17}/></button>}</div>}</div></Card>})}</div>
    <Modal open={!!editing} onClose={()=>setEditing(null)} title={isAr?'تعديل عضو الفريق':'Edit team member'} size="lg" footer={<><Btn variant="secondary" onClick={()=>setEditing(null)}>{isAr?'إلغاء':'Cancel'}</Btn><Btn disabled={pending||!editing?.name?.trim()||!editing?.roleIds?.length||!editing?.primaryRoleId} onClick={save}>{pending?'…':(isAr?'حفظ التغييرات':'Save changes')}</Btn></>}><div className="space-y-4"><Input label={isAr?'الاسم':'Name'} value={editing?.name||''} onChange={event=>setEditing(current=>({...current,name:event.target.value}))}/><Input label={isAr?'البريد الإلكتروني':'Email'} value={editing?.email||''} readOnly/><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Input label={isAr?'الهاتف':'Phone'} value={editing?.phone||''} onChange={event=>setEditing(current=>({...current,phone:event.target.value}))}/><Input label={isAr?'واتساب':'WhatsApp'} value={editing?.whatsapp||''} onChange={event=>setEditing(current=>({...current,whatsapp:event.target.value}))}/></div><RolePicker roles={store.worshipRoles} selected={editing?.roleIds||[]} onChange={roleIds=>setEditing(current=>({...current,roleIds,primaryRoleId:roleIds.includes(current.primaryRoleId)?current.primaryRoleId:(roleIds[0]||'')}))} isAr={isAr}/><Select label={isAr?'الدور الأساسي':'Primary role'} value={editing?.primaryRoleId||''} onChange={event=>setEditing(current=>({...current,primaryRoleId:event.target.value}))}><option value="">{isAr?'اختر الدور الأساسي':'Choose primary role'}</option>{store.worshipRoles.filter(role=>editing?.roleIds?.includes(role.id)).map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</Select><Select label={isAr?'صلاحية النظام':'System access'} value={editing?.accessLevel||'member'} disabled={!isSuperAdminUser(store.currentUser)&&['super_admin','admin'].includes(editing?.accessLevel)} onChange={event=>setEditing(current=>({...current,accessLevel:event.target.value}))}>{(isSuperAdminUser(store.currentUser)?['super_admin','admin','leader','member']:['leader','member']).map(level=><option key={level} value={level}>{ACCESS_LEVEL_LABELS[level][isAr?'ar':'en']}</option>)}</Select><Select label={isAr?'حالة الحساب':'Account status'} value={editing?.status||'active'} onChange={event=>setEditing(current=>({...current,status:event.target.value}))}><option value="active">{isAr?'نشط':'Active'}</option><option value="inactive">{isAr?'غير نشط':'Inactive'}</option><option value="on-leave">{isAr?'إجازة':'On leave'}</option></Select><Textarea label={isAr?'ملاحظات':'Notes'} value={editing?.notes||''} onChange={event=>setEditing(current=>({...current,notes:event.target.value}))}/>{error&&<p className="text-sm text-red-600" role="alert">{error}</p>}</div></Modal>
    <ConfirmDialog open={!!deactivate} onClose={()=>setDeactivate(null)} title={isAr?'تعطيل عضو الفريق؟':'Deactivate team member?'} message={isAr?`لن يتمكن ${deactivate?.name||''} من تسجيل الدخول، وستبقى سجلاته التاريخية محفوظة.`:`${deactivate?.name||''} will no longer be able to sign in. Historical records remain intact.`} confirmLabel={isAr?'تعطيل':'Deactivate'} onConfirm={async()=>{const result=await store.deletePerson(deactivate.id);if(!result?.error)setDeactivate(null);return result}}/>
  </div>
}

function PermissionsPanel({store,isAr}){
  const [draft,setDraft]=useState(store.permissionMatrix);const[pending,setPending]=useState('');const[error,setError]=useState('');const canEdit=isSuperAdminUser(store.currentUser)
  const toggle=(level,key)=>setDraft(previous=>({...previous,[level]:(previous[level]||[]).includes(key)?previous[level].filter(item=>item!==key):[...(previous[level]||[]),key]}))
  const save=async level=>{setPending(level);setError('');const result=await store.updateAccessPermissions(level,draft[level]||[]);setPending('');if(result?.error)setError(result.error)}
  return <div className="space-y-4"><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm text-indigo-800"><Shield className="me-2 inline" size={17}/>{isAr?'أدوار التسبيح منفصلة تماماً عن صلاحيات النظام. المسؤول الأعلى يملك كل الصلاحيات دائماً.':'Worship roles are fully separate from system permissions. Super Admin always has every permission.'}</div><div className="grid grid-cols-1 gap-4 xl:grid-cols-3">{['admin','leader','member'].map(level=><Card key={level} className="p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-slate-800">{ACCESS_LEVEL_LABELS[level][isAr?'ar':'en']}</h3><KeyRound size={17} className="text-indigo-500"/></div><div className="space-y-2">{store.permissionDefinitions.map(permission=><label key={permission.permission_key} className="flex items-start gap-2 rounded-lg border border-slate-100 p-2.5 text-sm"><input type="checkbox" disabled={!canEdit} checked={(draft[level]||[]).includes(permission.permission_key)} onChange={()=>toggle(level,permission.permission_key)} className="mt-0.5"/><span><strong className="block text-slate-700">{permission.permission_key}</strong><span className="text-xs text-slate-400">{permission.description}</span></span></label>)}</div>{canEdit&&<Btn className="mt-4" size="sm" disabled={pending===level} onClick={()=>save(level)}>{pending===level?'…':(isAr?'حفظ الصلاحيات':'Save permissions')}</Btn>}</Card>)}</div>{!canEdit&&<p className="text-sm text-amber-700">{isAr?'يمكن للمسؤول الأعلى فقط تغيير مصفوفة الصلاحيات.':'Only a Super Admin can change the permission matrix.'}</p>}{error&&<p className="text-sm text-red-600" role="alert">{error}</p>}</div>
}

function InvitationsPanel({store,isAr,navigate}){return <div className="space-y-4"><div className="flex justify-end"><Btn icon={<UserPlus size={15}/>} onClick={()=>navigate('/invitations')}>{isAr?'إنشاء دعوة':'Create invitation'}</Btn></div>{store.invitations.length===0?<EmptyState icon={<UserPlus/>} title={isAr?'لا توجد دعوات':'No invitations'}/>:<div className="space-y-2">{store.invitations.map(invitation=><Card key={invitation.id} className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong className="text-sm text-slate-800">{invitation.email}</strong><p className="text-xs text-slate-500">{(invitation.roles||[]).join(' · ')} · {ACCESS_LEVEL_LABELS[invitation.accessLevel||invitation.access_level||'member']?.[isAr?'ar':'en']}</p></div><div className="flex items-center gap-2"><Badge color={invitation.status==='pending'?'yellow':invitation.status==='accepted'?'green':'slate'}>{invitation.status}</Badge>{invitation.status!=='accepted'&&<Btn size="xs" variant="secondary" onClick={()=>store.renewInvitation(invitation.id)}>{isAr?'تجديد':'Renew'}</Btn>}</div></div></Card>)}</div>}</div>}

export default function AdminControl(){
  const store=useStore();const{isAr}=useLang();const navigate=useNavigate();const[tab,setTab]=useState('overview')
  const tabs=useMemo(()=>[
    {value:'overview',label:isAr?'نظرة عامة':'Overview'},
    {value:'users',label:isAr?'أعضاء الفريق':'Team members',permission:'users.view'},
    {value:'roles',label:isAr?'الأدوار والآلات':'Roles & instruments',permission:'roles.manage'},
    {value:'permissions',label:isAr?'الصلاحيات':'Permissions',permission:'permissions.manage'},
    {value:'invitations',label:isAr?'الدعوات':'Invitations',permission:'invitations.manage'},
    {value:'settings',label:isAr?'إعدادات النظام':'System settings',permission:'settings.manage'},
  ].filter(item=>!item.permission||hasPermission(store.currentUser,item.permission)),[isAr,store.currentUser])
  return <div className="mx-auto max-w-7xl space-y-5"><div className="rounded-2xl bg-gradient-to-r from-slate-900 to-indigo-900 p-6 text-white"><div className="flex items-center gap-3"><div className="rounded-xl bg-white/10 p-3"><Settings2/></div><div><h1 className="text-2xl font-bold">{isAr?'التحكم الإداري':'Admin Control'}</h1><p className="mt-1 text-sm text-indigo-200">{isAr?'المصدر المركزي للأدوار والمستخدمين والصلاحيات وإعدادات المنصة':'Central management for roles, users, permissions, and platform settings'}</p></div></div></div><Tabs tabs={tabs} active={tab} onChange={setTab}/>{tab==='overview'?<Overview store={store} isAr={isAr} onTab={setTab} navigate={navigate}/>:tab==='roles'?<RolesPanel store={store} isAr={isAr}/>:tab==='users'?<UsersPanel store={store} isAr={isAr}/>:tab==='permissions'?<PermissionsPanel store={store} isAr={isAr}/>:tab==='invitations'?<InvitationsPanel store={store} isAr={isAr} navigate={navigate}/>:<div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Card className="p-5"><h2 className="font-semibold text-slate-800">{isAr?'إعدادات المؤسسة':'Organization settings'}</h2><p className="my-3 text-sm text-slate-500">{isAr?'اسم الكنيسة والمنطقة الزمنية وإعدادات الحضور.':'Church name, timezone, and attendance configuration.'}</p><Btn variant="secondary" onClick={()=>navigate('/settings')}>{isAr?'فتح الإعدادات':'Open settings'}</Btn></Card><Card className="p-5"><h2 className="font-semibold text-slate-800">{isAr?'سجل التدقيق':'Audit log'}</h2><p className="my-3 text-sm text-slate-500">{isAr?'يتم تسجيل تغييرات الأدوار والمستخدمين والصلاحيات والدعوات تلقائياً.':'Role, user, permission, and invitation changes are recorded automatically.'}</p><Badge color="green">{store.auditLogs.length} {isAr?'سجل':'entries'}</Badge></Card></div>}</div>
}
